version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: release-it
    versions:
    - 14.2.2
    - 14.3.0
    - 14.4.0
    - 14.4.1
    - 14.5.0
    - 14.5.1
    - 14.6.0
  - dependency-name: superstruct
    versions:
    - 0.14.0
    - 0.14.1
    - 0.14.2
    - 0.15.0
  - dependency-name: pino
    versions:
    - 6.11.0
    - 6.11.1
    - 6.11.2
  - dependency-name: pino-pretty
    versions:
    - 4.3.0
    - 4.4.0
    - 4.5.0
    - 4.6.0
