version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.10

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  test:
    <<: *defaults  
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run:
          name: Run tests
          command: npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .
  build: 
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      
      - run: 
          name: Build project
          command: npm run build
      
      - persist_to_workspace:
          root: ~/repo
          paths: .    
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: npm publish
      - run: 
          name: Publish coverage files to Codecov
          command: ./node_modules/.bin/codecov
            
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/  
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
